on: push

name: Continuous integration

jobs:
  ci:
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Caching
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --workspace --all-targets
      - name: Run tests
        run: cargo test --workspace --all-targets
      - name: Run tests with system lzfse
        run: cargo test --workspace --features system-lzfse --all-targets
      - name: Run tests with only zlib
        run: cargo test --workspace --no-default-features --features zlib --all-targets

      - name: Test formatting
        run: cargo fmt --all -- --check

      - name: Check for clippy warnings
        run: cargo clippy --workspace --all-targets -- -D warnings
